name: Deploy library
on:
  release:
    types: [published]

jobs:
  build:
    if: ${{ github.repository == 'AlexanderEggers/ksecurestorage' }}
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Release library
        run: ./gradlew ksecurestorage:publish
        env:
          RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}
          GH_USER: ${{ secrets.GH_USER }}
          GH_TOKEN: ${{ secrets.GH_PUBLISH_TOKEN }}